### ISSUE TITLE
Add a feature to get words from a local text file

### ISSUE THREAD

**Issue by tshrinivasan** [manimaran96/Spell4Wiki#12]
along with getting words from the wiktionary category for any language, add a feature to get words from a local text file.

- [x] open the file
- [x] read a word
- [x] check if it is available in commons
- [x] if not there, show for recording
repeat.

**Comment by manimaran96** [comment]
@tshrinivasan 
In this(a8a08950cc4565b472ae78fca24e84d8ac860755) commit i added this feature.

Upload words if not exist in commons. Otherwise removed word from list.
Check if it is available in commons - need to done.

**Comment by manimaran96** [comment]
Along with getting words from the wiktionary category for any language, we implemented following features...

1. Import words from text file then record audio
2. Copy & Paste content then record audio
3. Directly type word then record audio

<img width="200" height="380" src="https://manimaran96.files.wordpress.com/2020/02/7_spell4wordlist.jpg"><img width="200" height="380" src="https://manimaran96.files.wordpress.com/2020/02/7_spell4wordlist6606178122206268153.jpg"><img width="200" height="380" src="https://manimaran96.files.wordpress.com/2020/02/10_spell4word815042023348816238.jpg">
