### ISSUE TITLE
App asks to login everytime

### ISSUE THREAD

**Issue by tshrinivasan** [manimaran96/Spell4Wiki#13]
Make sure the app login is saved and not asked everytime

**Comment by tshrinivasan** [comment]
check this repo for keeping login across sessions
https://github.com/Atul22/wikiAudio

**Comment by manimaran96** [comment]
> check this repo for keeping login across sessions
> https://github.com/Atul22/wikiAudio

Check this line 
https://github.com/manimaran96/Spell4Wiki/blob/master/app/src/main/java/com/manimaran/wikiaudio/wiki_api/ServiceGenerator.java#L75

In this line, we getting cookie values after the login.
We need to store and re-use the cookie.

**Comment by manimaran96** [comment]
Fixed. By using sync adapter - authenticator

Ref : [Wiki - Commons App](https://github.com/wikimedia/apps-android-wikipedia/blob/d9ebccbada0c028fd914c6c3e85fc74361b716de/app/src/main/java/org/wikipedia/auth/AccountUtil.java#L138)
