### ISSUE TITLE
download option from f-droid

### ISSUE THREAD

**Issue by tha-uzhavan** [manimaran96/Spell4Wiki#25]
https://f-droid.org/en/about/ என்ற தளத்தில் இருந்து பதிவிறக்கம் செய்ய நாம் ஊக்குவிக்க வேண்டும். நிறைய பேருக்கு அறிமுகம் செய்தது போலவும் இருக்கும். கூகுள் தளமும் இருக்கட்டும்.

**Comment by manimaran96** [comment]
@tha-uzhavan, We started the process publishing app in F-Droid also, I hope quickly available in F-Droid.
You can look [here](https://gitlab.com/fdroid/rfp/-/issues/1490) the more details.
