### ISSUE TITLE
Direct audio run icon 

### ISSUE THREAD

**Issue by tha-uzhavan** [manimaran96/Spell4Wiki#27]
![spell4wiki-soundiconRun](https://user-images.githubusercontent.com/8150806/85492127-50c4a880-b5f2-11ea-88e3-b92c44920fe8.jpg)
பதிவேற்றிய ஒலிப்புக்கோப்பினை, உடனடியாக விக்சனரியில் கேட்க முடிகிறது. மிக்க மகிழ்ச்சி.  ஆனால், படத்தில் காட்டியபடி வரும் மூன்று புள்ளிகளை அழுத்தினால், தோன்றும் இயக்கு என்ற வசதியை அழுத்தினால் மட்டுமே கேட்க முடிகிறது. நேரடியாக கோப்பினை இயக்க, விக்சனரி தளத்தில் இருப்பது போல, அம்பு குறியை அழுத்தினால் ஒலிப்பு கேட்க வழிமுறை செய்யுங்கள்.

**Comment by manimaran96** [comment]
ஆம், கைப்பேசிகளில் இவ்வாறுதான் தோற்றமளிக்கிறது, அது விக்சனரியின்  இணைய பக்கமாகும் அதில் நமது மொபைல் செயலி மூலம் ஏதும் மாற்றம் செய்ய இயலாது. தமிழ் விக்சனரியின் இணைய பக்கத்தில் மாற்றத்தை செய்தாலே சரியாகும்.
