### ISSUE TITLE
Make it to use with any language wiktionary

### ISSUE THREAD

**Issue by tshrinivasan** [manimaran96/Spell4Wiki#3]
Make it to use with any language wiktionary

**Comment by manimaran96** [comment]
This JSON file have all wiki language list.
https://github.com/manimaran96/Spell4Wiki/blob/master/files/lang-json/language.json
If missing any language any one can add to this file. Then, automatically reflected in app.

![photo6107180119383714610](https://user-images.githubusercontent.com/13943321/54921573-18847500-4f2c-11e9-8941-f63995b70336.jpg)

**Note**
"code": "ta",  --> Language code
"lang": "Tamil", --> Language common name 
"dir": "ltr", --> Language direction. ltr - left to right, rtl - right to left. 
"local_lang": "தமிழ்", --> Local language. 
"title_words_without_audio" : "பகுப்பு:தமிழ்-ஒலிக்கோப்புகளில்லை" --> Tag for set of words without audio. Currently this title only have in Tamil language. 
If created in other languages. After that need to update this file.

**In this app have two parts** 
1. Contribution to wiki commons.
2. Wiktionary surffing.

In Wiktionary mode we list all the languages.
Any time to switch any other language. 

In Contribution mode we list only If have "title_words_without_audio" key.
Now this key only have in Tamil. So, currently we list only Tamil in contribution mode.
