### ISSUE TITLE
Provide alternative solution for license selection.

### ISSUE THREAD

**Issue by lrmodesgh** [manimaran96/Spell4Wiki#30]
**Is your feature request related to a problem? Please describe.**
Selecting License for contribution seems not to make sense for users who are not aware about the seriousness of license. For example my partner, or family....

**Describe the solution you'd like**
Make the license defaulted to CC0 or a dialog box showing different licenses to select from can be provided to the user after reviewing the recording.

**Describe alternatives you've considered**
There is mild understanding of what the word "wiki" means in general. We can utilitze that abstract understanding to make the default as CC0. Furthermore, while recording the licensing check box is creating a block in the UX flow. The other method might help users to know and learn what are all the creative commons (counter copyright) licenses are available (provide a link to cc website too).

**Additional context**
the default can be changed in settings menu. Even there the license space shall be limited to creative commons spectrum without any option for making the contribution private or proprietary.

**Comment by manimaran96** [comment]
Fixed

![s4w-2](https://user-images.githubusercontent.com/13943321/221375879-eed8998f-fa86-4760-9dfd-4f9a9fa556ab.png)
