### ISSUE TITLE
Adding Odia

### ISSUE THREAD

**Issue by psubhashish** [manimaran96/Spell4Wiki#33]
**Provide following information**

* Language name : Odia
* Language code : or
* Language direction : LTR
* Local name : ଓଡ଼ିଆ
* Category name in Wiktionary : ଶ୍ରେଣୀ:
* Category name in Commons : Category:

Ref : [More details](https://github.com/manimaran96/Spell4Wiki/blob/master/docs/CONTRIBUTING.md#add-your-wiktionary-language-into-spell4wiki)

**Comment by manimaran96** [comment]
Hi @psubhashish thanks for your contribution. 
Can you please give full link for both category ? 

For your reference 
- https://docs.google.com/spreadsheets/d/14c8s7UN-8eCDA-qU73l_yXhLdxdjYfuzubAl9RrehuQ/edit?usp=sharing
- https://github.com/manimaran96/Spell4Wiki/blob/master/docs/CONTRIBUTING.md#add-your-wiktionary-language-into-spell4wiki

**Comment by psubhashish** [comment]
Sorry for getting back late. The category on Odia Wiktionary is "[ଶ୍ରେଣୀ:ଓଡ଼ିଆ_ଭାଷା](https://or.wiktionary.org/wiki/%E0%AC%B6%E0%AD%8D%E0%AC%B0%E0%AD%87%E0%AC%A3%E0%AD%80:%E0%AC%93%E0%AC%A1%E0%AC%BC%E0%AC%BF%E0%AC%86_%E0%AC%AD%E0%AC%BE%E0%AC%B7%E0%AC%BE)" and for Commons is https://commons.wikimedia.org/wiki/Category:Files_uploaded_by_spell4wiki_in_or

**Comment by manimaran96** [comment]
Thanks @psubhashish 
I will update shortly. 
I used this category words : https://or.wiktionary.org/s/qer

ଶ୍ରେଣୀ:ଓଡ଼ିଆ ଦେଶଜ ଶବ୍ଦ

**Comment by manimaran96** [comment]
Odia language added in spell for wiktionary option.
Thanks for your contribution. 
Further updates visit : https://commons.wikimedia.org/wiki/Commons:Spell4Wiki

**Comment by psubhashish** [comment]
Hi @manimaran96: not sure why you used "ଶ୍ରେଣୀ:ଓଡ଼ିଆ ଦେଶଜ ଶବ୍ଦ" as a category. "ଓଡ଼ିଆ ଦେଶଜ ଶବ୍ଦ" literally means native Odia words. However words that are influenced/derived from other languages are in active use which is why I proposed an umbrella category "ଶ୍ରେଣୀ:ଓଡ଼ିଆ_ଭାଷା". Is there an issue using "ଶ୍ରେଣୀ:ଓଡ଼ିଆ_ଭାଷା"?

**Comment by manimaran96** [comment]
Hi @psubhashish 
Actually you provided category doesn't have words list. Only have some sub categories like 

```
ସାନ ଶ୍ରେଣୀସମୂହ

ଏହି ଶ୍ରେଣୀଟିରେ ସର୍ବମୋଟ ୪ ରୁ ତଳେଥିବା ଏହି ୪ ଶ୍ରେଣୀଗୁଡିକ ଅଛନ୍ତି ।
ଓ

ଓଡ଼ିଆ ଦେଶଜ ଶବ୍ଦ‎ (୬ ପୃଷ୍ଠା)
ଓଡ଼ିଆ ବର୍ଣ୍ଣମାଳା‎ (୫ ପୃଷ୍ଠା)
ଓଡ଼ିଆ ବିଶେଷଣ‎ (୧ ପୃଷ୍ଠା)
ଓଡ଼ିଆ ବିଶେଷ୍ୟ‎ (୪ ପୃଷ୍ଠା)
```

you can record only above title words only not for words. so that i used "ଓଡ଼ିଆ ଦେଶଜ ଶବ୍ଦ" this one. bcz this have 6 words. 
If you want to add this category then add some words below ଶ୍ରେଣୀ:ଓଡ଼ିଆ ଭାଷା

**Comment by psubhashish** [comment]
It still should be "ଶ୍ରେଣୀ:ଓଡ଼ିଆ ଭାଷା" (which now has more words). I think I probably need some help to put words into categories. We also need to figure out a way to put words into a separate category that does **NOT** already have a pronunciation. As you'd see there are more than [3,700 pronunciations](https://commons.wikimedia.org/wiki/Category:Lingua_Libre_pronunciation-ory,_ori) recorded alone using Lingua Libre and there are more that were recorded using other ways (including the command-line tool that Shrini built years ago). One might argue that the more number of pronunciation you have for the same word the better as you could capture diversity (gender wise, accent wise and other demographic areas) which is true. But we also need to have a category to distinguish words that do not have any pronunciation at all so that those who are going to record can make an informed decision. Is there any tool that you or others recommend to categorize word entries on Wiktionary?

**Comment by manimaran96** [comment]
> It still should be "ଶ୍ରେଣୀ:ଓଡ଼ିଆ ଭାଷା" (which now has more words). I think I probably need some help to put words into categories. We also need to figure out a way to put words into a separate category that does **NOT** already have a pronunciation. As you'd see there are more than [3,700 pronunciations](https://commons.wikimedia.org/wiki/Category:Lingua_Libre_pronunciation-ory,_ori) recorded alone using Lingua Libre and there are more that were recorded using other ways (including the command-line tool that Shrini built years ago). One might argue that the more number of pronunciation you have for the same word the better as you could capture diversity (gender wise, accent wise and other demographic areas) which is true. But we also need to have a category to distinguish words that do not have any pronunciation at all so that those who are going to record can make an informed decision. Is there any tool that you or others recommend to categorize word entries on Wiktionary?

@psubhashish 
Ok, I will change to "ଶ୍ରେଣୀ:ଓଡ଼ିଆ ଭାଷା"

About to categories tool you can contact [Indo-farmer](https://www.mediawiki.org/wiki/User:Info-farmer).

**Comment by manimaran96** [comment]
@psubhashish 
Updated with you mentioned category. 


**Ref :**
https://github.com/manimaran96/Spell4Wiki/blob/664b27654d1fcac0312dd2b0217fd58673eb077f/files/base_data/spell4wiki_base.json#L29
