### ISSUE TITLE
New Features Request I wish to contribute. Pl approve/comment

### ISSUE THREAD

**Issue by msj2** [manimaran96/Spell4Wiki#40]
**Is your feature request related to a problem? Please describe.**
*  I'm frustrated when I need to click Accepted Terms & Conditions Checkbox in each upload
* I'm frustrated when I see words which already have audio files
* I'm frustrated when Audio file is not linked to Wiktionary word
* I'm frustrated when I need to upload audio file for same word in multiple WIktionaries separately
* I'm frustrated when I can't see words categorized by some Order, say Games, Chemistry, .....
* I'm frustrated when I see ogg instead of ogg or mp3 or m4a
* Reduce install APK size by 500 KB 

**Describe the solution you'd like**
Put Codefixes for these, provided these are accepted as good to have, in a period of 90 days.

**Describe alternatives you've considered**
At this point none.

**Additional context**

**Comment by manimaran96** [comment]
Thanks @msj2 
Below I shared some comments,


> I'm frustrated when I need to click Accepted Terms & Conditions Checkbox in each upload

Yes agree, will give option in settings and first time of upload. 

> I'm frustrated when I can't see words categorized by some Order, say Games, Chemistry, .....

Currently Spell4Wiki app support only one category words. In future we plan to support search based categories.

 > Reduce install APK size by 500 KB

APK size already we do our best. we reduced almost. 
then, 500KB size apk not possible.

@tha-uzhavan please give your comments for other points.

**Comment by tha-uzhavan** [comment]
@msj2 When we started this project few years before, my main aim is to reduce Tamil wiktionary practices and  its contributed related frustations. WMF dropped two times this kind of Android app project. becoz wiktionary [exsists more than 180 languages.](https://meta.wikimedia.org/wiki/Wiktionary#List_of_Wiktionaries) Its very hard to handle with all the needs of every language wiktionary. Every local wiktionary community consensus is differs. If you show your community needs with the consensus as a wiktionary page, we will try to fulfill your community needs in our time. We can make  a  wiktionary movement for this app with other Indic language contributors. Make a try at CIS. We need fund as well as atleast two contributors from each Indic wiktionary. WMF is interesting in wikidata lexeme project only. Writing this app related codes and changing the previous code also is not easy. This is a one man army. All the uploaded words are available[ in your wiktionary with out any issues.](https://kn.wiktionary.org/wiki/%E0%B2%B8%E0%B2%A6%E0%B2%B8%E0%B3%8D%E0%B2%AF:Info-farmer/pronunciation_audio_files_kn) There are few changes to be done in every local language. we, Tamil wiktionary discussing to our needs. Please start a dissusion at your wiktionary. Individual need may be differ from a vommunity need. without the community consensus, nothing is possible in any WMF projects..

**Comment by manimaran96** [comment]
Fixed possible issues and few issues related to Wikimedia categories and template.
