### ISSUE TITLE
Include Tulu (tcy) in the language drop down on Spell4Wiki Android Application

### ISSUE THREAD

**Issue by Alasande** [manimaran96/Spell4Wiki#41]
**Provide following information**

* Language name :Tulu
* Language code :tcy
* Language direction :
* Local name :Tulu
* Category name in Wiktionary : Tulu
* Category name in Commons :Tulu 

Ref : [More details](https://github.com/manimaran96/Spell4Wiki/blob/master/docs/CONTRIBUTING.md#add-your-wiktionary-language-into-spell4wiki)

**Comment by manimaran96** [comment]
Fixed 5a9481c
