### ISSUE TITLE
Add Spanish Language

### ISSUE THREAD

**Issue by ghost** [manimaran96/Spell4Wiki#46]
**Provide following information**

* Language name : Spanish
* Language code : es
* Language direction : left to right
* Local name : Español
* Category name in Wiktionary : https://es.wiktionary.org
* Category name in Commons : https://es.wikipedia.org/wiki/Wikipedia_en_espa%C3%B1ol

Ref : [More details](https://github.com/manimaran96/Spell4Wiki/blob/master/docs/CONTRIBUTING.md#add-your-wiktionary-language-into-spell4wiki)

I am not sure about the category names, but Spanish is an important language in Wikipedia. 

**Could we please add Spanish Language in the application ?**

Thanks !

**Comment by manimaran96** [comment]
@marreromarco 

Kindly check this link : https://github.com/manimaran96/Spell4Wiki/blob/master/docs/CONTRIBUTING.md#add-your-wiktionary-language-into-spell4wiki

**Category name in Wiktionary** -> Which is help to show list of words from Wiktionary. Better to mention in category of words without have audio or mention any category to be need audio.
    
 **Category name in Commons** -> All audio files are uploaded under this commons category.  So, share your language specific audio category. If have more category then separate with coma(,).

**Comment by manimaran96** [comment]
Closed this issue no response from reporter @ghost
Anyway, we plan to give feature to add category in app.
