### ISSUE TITLE
Please add Urdu Language

### ISSUE THREAD

**Issue by abusarimhindi** [manimaran96/Spell4Wiki#48]
**Provide following information**

* Language name : Urdu
* Language code : Ur
* Language direction : RTL
* Local name : اُردو
* Category name in Wiktionary :  [زمرہ:اردو_زبان](https://ur.wiktionary.org/wiki/زمرہ:اردو_زبان#ا)
* Category name in Commons : Files uploaded by spell4wiki in ur,
Urdu pronunciation of the words with Urdu script

Ref : [More details](https://github.com/manimaran96/Spell4Wiki/blob/master/docs/CONTRIBUTING.md#add-your-wiktionary-language-into-spell4wiki)

**Comment by manimaran96** [comment]
Added in 9bbb0da
