### ISSUE TITLE
Flow to exit the app seems needlessly cumbersome

### ISSUE THREAD

**Issue by sivaraam** [manimaran96/Spell4Wiki#5]
The app seems to use a mixup of 2 methods:

1. Hitting back twice to exit
2. Ask for confirmation on exit

I guess using either of those approaches is enough. I personally prefer the former as it does not require me to move my finger to complete the action of exiting ;-) Personally, I also don't like pop-ups a lot.

**Comment by sivaraam** [comment]
*Screen shot*
![complex exit sequence](https://user-images.githubusercontent.com/12448084/51086915-51f17500-1772-11e9-8ade-c007cc565e7f.png)

The message in the toast is misleading. I'm asked whether to exit the app via the prompt despite the toast mentioning I can exit the app by hitting back again.

**Comment by manimaran96** [comment]
Finalized, Hitting back twice to exit.
