### ISSUE TITLE
Trademark issue with app logo?

### ISSUE THREAD

**Issue by sivaraam** [manimaran96/Spell4Wiki#6]
I think it's a trademark issue to use the Wikimedia foundation, Wiktionary logo without their consent. It's not an issue if it is used after asking them for the permission.

Regardless, using the WMF logo as the app icon doesn't seem so suitable to it.

**Comment by manimaran96** [comment]
Need to check this links

https://foundation.wikimedia.org/wiki/Wikimedia_trademarks
https://foundation.wikimedia.org/wiki/Trademark_policy

**Comment by manimaran96** [comment]
@lrmodesgh  logo designed for spell4wiki.

https://github.com/manimaran96/Spell4Wiki/blob/master/app/src/main/res/drawable/spell4wiki.png
