### ISSUE TITLE
Make unique language selection options for Wikimedia contribution

### ISSUE THREAD

**Issue by manimaran96** [manimaran96/Spell4Wiki#62]
- [ ] When landing the app user need to select the WIkimedia language too. Like app language 
- [ ] Remove multiple settings option in settings page. 
- [ ] All pages should follow the same selected language 

![s4w-screen-2](https://user-images.githubusercontent.com/13943321/221008092-4dbc48cb-b691-457a-bd15-ee3a1541402f.jpeg)

**Comment by SEENUVASANINDIA** [comment]
solved

**Comment by SEENUVASANINDIA** [comment]
issue rectified
