### ISSUE TITLE
Missing upload button

### ISSUE THREAD

**Issue by sivaraam** [manimaran96/Spell4Wiki#7]
I don't see the upload button even after I record the audio. I see the upload button in the screen shot posted in [the blog](https://manimaran96.wordpress.com/2019/01/06/spell4wiki-mobile-app-to-record-upload-audio-for-wiktionary/).

### Screen shot
![missing upload button](https://user-images.githubusercontent.com/12448084/51086863-97617280-1771-11e9-9144-f5f9f7610b0e.png)

### Device information
*Device*: Samsung Galaxy J1 ace
*Android version*: 5.1.1
*Screen size*: 4.3"

**Comment by manimaran96** [comment]
https://github.com/manimaran96/Spell4Wiki/releases/download/dev_app3/spell4wiki_v3.apk
Try this apk.
