### ISSUE TITLE
Language option cannot be changed permanently

### ISSUE THREAD

**Issue by anil-al** [manimaran96/Spell4Wiki#85]
**Describe the bug**
The new option for language choosing doesn't work and it only temporarily changes. It reverts back to Tamil.

**Basic information**
- Spell4Wiki Version:2.0
- Android Version:13.0
- Device Name: Samsung TabS8
- Wikimedia Commons Username (optional):

**Steps to reproduce the behavior:**
1. Go to 'Search page and search for a term'
2. Click on 'language option (Tamil default) and change language'
3. Choose an article to open 
4. Article opens in Tamil instead of the chosen language.
5. Close app and see that it reverted back to default (Tamil)

**Expected behavior**
Language chosen should remain unchanged.

**Screenshots**

**Comment by anil-al** [comment]
I deleted the app and redownloaded. The problem has been fixed and it seems like this happens because even though I had chosen English for the contribution language previously, after the last update it changes to Tamil and there is no way to change it unless one reinstalls or delete the data of the app. Contribution language option should be added for that to be fixed to settings.

**Comment by manimaran96** [comment]
@anil-al  thanks for reporting 
Addressed this issue.
Can you check latest version 2.1

**Comment by manimaran96** [comment]
@anil-al app will live take 5 to 10hours.
