### ISSUE TITLE
Good to place the total no. of audio files loaded to Wiki Commons using Spell4Wiki

### ISSUE THREAD

**Issue by msj2** [manimaran96/Spell4Wiki#90]
**Is your feature request related to a problem? Please describe.**
Nope. In readme.md of this Repo, It is good to place the total no. of audio files loaded to Wiki Commons using Spell4Wiki

**Describe the solution you'd like**
Good to place the total no. of audio files loaded to Wiki Commons using Spell4Wiki

**Describe alternatives you've considered**
None 

**Additional context**
[spell4wiki-stats.csv](https://github.com/manimaran96/Spell4Wiki/files/13433824/spell4wiki-stats.csv)
As on Nov 22 2023

**Comment by manimaran96** [comment]
Thanks for suggetion 
Added here: [ spell4wiki_files_uploded_stats.png](https://github.com/manimaran96/Spell4Wiki/blob/master/README.md#stats-of-files-uploaded-by-speell4wiki-to-wikimedia-commons)
